tls:
  certificates:
    - certFile: /etc/traefik/certs/moodle-cert.pem
      keyFile: /etc/traefik/certs/moodle-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/moodle-cert.pem
        keyFile: /etc/traefik/certs/moodle-key.pem